### ISSUE TITLE
Can't handle vectors with dtype ```np.float32```. ```np.float64``` works just fine

### ISSUE THREAD

**Issue by Nitinsiwach** [weaviate/weaviate-python-client#1079]
### How to reproduce this bug?

```
jeopardy = client.collections.get("JeopardyQuestion")
uuid = jeopardy.data.insert(
    properties={
        "question": "This vector DB is OSS and supports automatic property type inference on import",
        "answer": "Weaviate",
    },
    vector= list(np.array([0.12345] * 1536, dtype = np.float32))
)
```

### What is the expected behavior?

The data should insert just fine

### What is the actual behavior?

1. If I insert one object with ```collections.data.insert``` Raises ```TypeError: Object of type float32 is not JSON serializable```
2. If I insert using ```collections.data.insert_many```. Doesnt use the vectors provided at all instead uses the default vectorizer provided in the yml used to create the client to vectorized the queries and the uses those vectors to store the object

### Server Version

1.25.0

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by tsmith023** [comment]
Your `1.` issue is fixed by this PR: https://github.com/weaviate/weaviate-python-client/pull/1077

However, I think your `2.` issue may actually be because you have a default vectorizer set in your `.yml` config but you are creating your collection, as posted on SO, like so:
```python
client.collections.create(name = "legal_sections", 
                          properties = [wvc.config.Property(name = "content",
                                                           description = "The actual section chunk that the answer is to be extracted from",
                                                           data_type = wvc.config.DataType.TEXT,
                                                           index_searchable = True,
                                                           index_filterable = True,
                                                           skip_vectorization = True,
                                                           vectorize_property_name = False)])
```
without specifying a vectoriser, so it defaults to the server default. Instead, you should add `vectorizer_config=wvc.config.Configure.Vectorizer.none()` to the `client.collections.create(...)` call.

Once `v4.6.3` is live, I would be grateful if you validate that it works then the issue can be closed 😁

**Comment by dirkkul** [comment]
please create a new issue if the mentioned PR does not solve your problem, thanks!
